backend:
  name: github
  repo: bdiehr/portfolio

media_folder: static/assets
public_folder: assets

collections:
  - name: blog
    label: Blog
    folder: data/blog
    create: true
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - { name: body, label: Body, widget: markdown }
  - name: portfolio
    label: Portfolio
    folder: data/portfolio
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Client", name: "client", widget: "string"}
      - {label: "Image", name: "img", widget: "image"}
      - {label: "Detail Image 1", name: "detail_img_1", widget: "image"}
      - {label: "Detail Image 2", name: "detail_img_2", widget: "image"}
      - {label: "Detail Image 3", name: "detail_img_3", widget: "image"}
      - {label: "Detail Image 4", name: "detail_img_4", widget: "image"}
      - {label: "Detail Image 5", name: "detail_img_5", widget: "image"}
  - name: brands
    label: Brands
    folder: data/brands
    create: true
    fields:
      - {label: "Client", name: "client", widget: "string"}
      - {label: "Description", name: "description", widget: "string"}
